============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/andriy/Olesya/Lab/Lab2
collected 5 items

tests/tests.py .....                                                     [100%]

============================== 5 passed in 0.81s ===============================
========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  04:26:28 PM
Date is:  12-27-2020
success
Добрий вечір!)
